apiVersion: v1
kind: Service
metadata:
  name: zipkin-service
  namespace: petfriends
spec:
  type: ClusterIP
  selector:
    app: zipkin
  ports:
  - port: 9411
    targetPort: 9411
    protocol: TCP
    name: http