apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  namespace: petfriends
spec:
  selector:
    app: zookeeper
  type: ClusterIP
  ports:
  - port: 2181
    targetPort: 2181
    protocol: TCP
    name: client

