apiVersion: v1
kind: Service
metadata:
  name: kibana-service
  namespace: petfriends
spec:
  type: ClusterIP
  selector:
    app: kibana
  ports:
  - port: 5601
    targetPort: 5601
    protocol: TCP
    name: http