apiVersion: v1
kind: ConfigMap
metadata:
  name: transporte-config
  namespace: petfriends
data:
  SERVER_PORT: "8083"
  SPRING_R2DBC_URL: "r2dbc:postgresql://postgres-service:5432/transporte_db"
  SPRING_FLYWAY_URL: "jdbc:postgresql://postgres-service:5432/transporte_db"
  SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS: "kafka-service:9093"
  ALMOXARIFADO_SERVICE_URL: "http://almoxarifado-internal:8082"
  LOGGING_LEVEL_ROOT: "INFO"
  LOGGING_LEVEL_COM_PETFRIENDS_TRANSPORTE: "DEBUG"
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: "http://zipkin-service:9411/api/v2/spans"
  LOGSTASH_HOST: "logstash-service"
  LOGSTASH_PORT: "5000"

