apiVersion: v1
kind: Service
metadata:
  name: logstash-service
  namespace: petfriends
spec:
  type: ClusterIP
  selector:
    app: logstash
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: tcp
  - port: 9600
    targetPort: 9600
    protocol: TCP
    name: http